name: Node Continuous Integration

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest # the VM environment to use
    steps:
      - uses: actions/checkout@v3 # checkout the code from the repository
      - uses: actions/setup-node@v3 # setup the node environment
        with:
          node-version: '25' # what node version to use in the VM environment
      - run: yarn clean
      - run: yarn install
      - run: yarn lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '25'
      - run: yarn clean
      - run: yarn install
      - run: yarn typecheck
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '25'
      - run: yarn clean
      - run: yarn install
      - run: yarn prettier
  test:
    needs: [lint, typecheck, prettier]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '25'
      - run: yarn clean
      - run: yarn install
      - run: yarn test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '25'
      - run: yarn clean
      - run: yarn install
      - run: yarn build